language: python
python:
  - "3.6.7"
# command to install dependencies
services:
  - postgresql
install: 
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c "CREATE DATABASE test_stacklite;" -U postgres
  - psql -c "CREATE DATABASE stacklite;" -U postgres
  - psql -c "CREATE USER blairtony WITH PASSWORD '1234';" -U postgres
# command to run tests
script: 
  - py.test --cov=app -v
after_success:
  - coveralls