#Language specification
language: python
python:
  - "3.6.7"
# Installing dependencies
services:
  - postgresql
install: 
  - pip3 freeze > requirements.txt
  - pip3 install -r requirements.txt
  - pip3 install coveralls
before_script:
  - psql -c "CREATE DATABASE test_stacklite;" -U postgres
  - psql -c "CREATE DATABASE stacklite;" -U postgres
  - psql -c "CREATE USER blairtony WITH PASSWORD '1234';" -U postgres
# Running tests
script: 
  - py.test --cov=app -v
after_success:
  - coveralls