#Language specification
language: python
python:
  - "3.6.7"
#branch to run on
branches:
    only:
      - develop
# Installing dependencies
services:
  - postgresql
install: 
  - pip3 install -r requirements.txt
  - pip3 install coveralls
before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE DATABASE stacklite_db;" -U postgres
  - psql -c "CREATE USER blairt001 WITH PASSWORD '1234';" -U postgres
# Running tests
script: 
  - py.test --cov=app -v
after_success:
  - coveralls